### ISSUE TITLE
Install additional packages

### ISSUE THREAD

**Issue by dorneanu** [aikinci/androguard#2]
Hi! Great work! Would it be possible to add additional packages to the default configuration?
- openssh-server
- ipython-notebook

Of course I can install them by myself (apt-get), but in case anybody needs them too.

Cheers,

Victor

**Comment by aikinci** [comment]
Hi Victor. Sorry I have overseen your issue. That is horrible. I am reworking on it now. Stay tuned.

**Comment by aikinci** [comment]
Ok it's done.
